'use client'
import { useMemo } from 'react'
import type { Teacher, ScheduleSlot } from '@/types'
import { calculateSalaries, formatBRL } from '@/lib/salary'
import styles from './PaymentTab.module.css'
interface Props {teachers:Teacher[];schedule:ScheduleSlot[];referenceWeek:string}
export default function PaymentTab({teachers,schedule,referenceWeek}:Props){
const result=useMemo(()=>calculateSalaries(referenceWeek||'—',teachers,schedule),[teachers,schedule,referenceWeek])
if(teachers.length===0)return(<div className={styles.empty}><div className={styles.emptyIcon}>💰</div><p>Nenhum dado para calcular</p><span>Cadastre professores e preencha a grade horária.</span></div>)
return(<div className={styles.root}><div className={styles.metrics}><div className={`card ${styles.metricCard}`}><div className={styles.metricLabel}>Aulas na semana</div><div className={styles.metricValue}>{result.summary.totalWeeklyClasses}</div></div><div className={`card ${styles.metricCard}`}><div className={styles.metricLabel}>Folha semanal</div><div className={`${styles.metricValue} ${styles.green}`}>{formatBRL(result.summary.totalWeeklyPay)}</div></div><div className={`card ${styles.metricCard} ${styles.metricHighlight}`}><div className={styles.metricLabel}>Folha mensal (4 semanas)</div><div className={`${styles.metricValue} ${styles.green}`}>{formatBRL(result.summary.totalMonthlyPay)}</div></div><div className={`card ${styles.metricCard}`}><div className={styles.metricLabel}>Professores</div><div className={styles.metricValue}>{result.summary.teacherCount}</div></div></div>{referenceWeek&&<p className={styles.weekLabel}>Semana de referência: <strong>{referenceWeek}</strong></p>}<div className={`card ${styles.tableCard}`}><h3 className={styles.tableTitle}>Detalhamento por professor</h3><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Professor</th><th>Disciplina</th><th>Aulas/sem</th><th>Horas</th><th>Valor/hora</th><th>Total semana</th><th>Total mês</th></tr></thead><tbody>{result.teachers.map(t=>(<tr key={t.id}><td><div className={styles.nameCell}><span className={styles.colorDot} style={{background:t.color}}/>{t.name}</div></td><td><span className="badge gray">{t.discipline}</span></td><td className={styles.number}>{t.weeklyCl}</td><td className={styles.number}>{t.totalHours.toFixed(1)}h</td><td className={styles.number}>{formatBRL(t.hourlyRate)}</td><td className={styles.number}>{formatBRL(t.weeklyPay)}</td><td className={`${styles.number} ${styles.monthlyTotal}`}>{formatBRL(t.monthlyPay)}</td></tr>))}</tbody><tfoot><tr className={styles.totalRow}><td colSpan={5}>Total geral</td><td className={styles.number}>{formatBRL(result.summary.totalWeeklyPay)}</td><td className={`${styles.number} ${styles.monthlyTotal}`}>{formatBRL(result.summary.totalMonthlyPay)}</td></tr></tfoot></table></div></div></div>)}
